name: Release Patch Version on Develop

on:
  push:
    branches:
      - develop

jobs:
  release-patch:
    if: github.event_name != 'workflow_run'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get gradle.properties from main branch
        run: |
          MAIN_GRADLE_PROPERTIES=$(git show main:gradle.properties)
          echo "$MAIN_GRADLE_PROPERTIES" > main-gradle.properties

      - name: Increment Patch Version
        id: increment_patch
        run: |
          # Read the current version from main-gradle.properties
          CURRENT_VERSION=$(grep '^version=' main-gradle.properties | cut -d'=' -f2)
          echo "Current Version (from main branch): $CURRENT_VERSION"

          # Increment the patch version using awk and maintain the dots
          UPDATED_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{$3+=1; print}')

          # Output the incremented version
          echo "Incremented Patch Version: $UPDATED_VERSION"
          echo "::set-output name=NEW_VERSION::$UPDATED_VERSION"

      - name: Create GitHub Package Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment_patch.outputs.NEW_VERSION }}
          release_name: Release v${{ steps.increment_patch.outputs.NEW_VERSION }}
          body: |
            Automatic patch version release: v${{ steps.increment_patch.outputs.NEW_VERSION }}
          draft: false
          prerelease: false
