name: Version Bump and Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Grant execute permission to the script
        run: chmod +x ./increment_version.sh
        
      - name: Run version increment script
        run: ./increment_version.sh

      - name: Archive Source Files
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump-version.outputs.new_version }}
          release_name: Release v${{ steps.bump-version.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Upload Source Code
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: .
