name: Release Patch Version on Develop

on:
  push:
    branches:
      - develop

jobs:
  release-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Extract Base Version
        id: extract_base_version
        run: |
          BASE_VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)
          echo "Base Version: $BASE_VERSION"
          echo "::set-output name=BASE_VERSION::$BASE_VERSION"

      - name: Increment Patch Version
        id: increment_patch
        run: |
          sed -i 's/\(version=\).*$/\1PATCH/' gradle.properties
          VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)
          echo "Incremented Patch Version: $VERSION"
          echo "::set-output name=NEW_VERSION::$VERSION"

      - name: Create GitHub Package Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment_patch.outputs.NEW_VERSION }}
          release_name: Release v${{ steps.increment_patch.outputs.NEW_VERSION }}
          body: |
            Automatic patch version release: v${{ steps.increment_patch.outputs.NEW_VERSION }}
          draft: false
          prerelease: false
