name: Release Minor Version on Main

on:
  push:
    branches:
      - main

jobs:
  release-minor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Extract Base Version and Increment Minor Version
        id: extract_and_increment_minor
        run: |
          # Extract base version from gradle.properties
          BASE_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "Base Version: $BASE_VERSION"

          # Split the base version into components
          IFS='.' read -ra VERSION_PARTS <<< "$BASE_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"

          # Increment the minor version component
          ((MINOR++))

          # Form the updated version
          UPDATED_VERSION="$MAJOR.$MINOR.$PATCH"

          # Update the gradle.properties file with the new version
          sed -i "s/^version=.*$/version=$UPDATED_VERSION/" gradle.properties
          echo "Incremented Minor Version: $UPDATED_VERSION"

          # Set the output for subsequent steps
          echo "::set-output name=NEW_VERSION::$UPDATED_VERSION"

      - name: Create GitHub Package Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_and_increment_minor.outputs.NEW_VERSION }}
          release_name: Release v${{ steps.extract_and_increment_minor.outputs.NEW_VERSION }}
          body: |
            Automatic minor version release: v${{ steps.extract_and_increment_minor.outputs.NEW_VERSION }}
          draft: false
          prerelease: false
