name: Release Minor Version on Main

on:
  push:
    branches:
      - main

jobs:
  release-minor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Read and Increment Minor Version
        id: increment_minor
        run: |
          # Read the current version from gradle.properties
          CURRENT_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "Current Version: $CURRENT_VERSION"

          # Increment the minor version using awk and maintain the dots
          UPDATED_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{split($2,a,"."); $2=a[1]+1 "." a[2] "." a[3]}1')

          # Update the gradle.properties file with the new version
          sed -i "s/^version=.*$/version=$UPDATED_VERSION/" gradle.properties
          echo "Incremented Minor Version: $UPDATED_VERSION"
          echo "::set-output name=NEW_VERSION::$UPDATED_VERSION"

      - name: Create GitHub Package Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment_minor.outputs.NEW_VERSION }}
          release_name: Release v${{ steps.increment_minor.outputs.NEW_VERSION }}
          body: |
            Automatic minor version release: v${{ steps.increment_minor.outputs.NEW_VERSION }}
          draft: false
          prerelease: false
