name: Version Bump and Release
permissions:
  contents: write

on:
  push:
    branches:
      - main
      - develop

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set execute permission
        run: chmod +x ./gradlew

      - name: Increment Semantic Version
        run: |
          #!/bin/bash
        
          if [[ "${GITHUB_EVENT_NAME}" == "push" && $(git log -1 --pretty=%B) == *"[MAJOR]"* ]]; then
            ./gradlew incrementSemanticVersion --major
          elif [[ "${GITHUB_EVENT_NAME}" == "push" && $(git log -1 --pretty=%B) == *"[MINOR]"* ]]; then
            ./gradlew incrementSemanticVersion --minor
          else
            ./gradlew incrementSemanticVersion --patch
          fi

      - name: Archive Source Files
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump-version.outputs.new_version }}
          release_name: Release v${{ steps.bump-version.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Upload Source Code
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: .
