name: Update Gradle Properties from Main to Develop

on:
  push:
    branches:
      - main

jobs:
  update-gradle-properties:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Main's Gradle Properties into Develop
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          # Fetch the latest changes for develop
          git fetch origin develop

          # Check differences in gradle.properties
          if git diff --exit-code origin/develop origin/main -- gradle.properties; then
            echo "No differences found in gradle.properties."
          else
            echo "Differences found in gradle.properties. Proceeding with merge."

            # Checkout the gradle.properties file from main into develop without committing
            git checkout origin/main -- gradle.properties

            # Overwrite the gradle.properties file in the develop branch
            git checkout develop
            git checkout --theirs origin/main -- gradle.properties

            # Stage the changes
            git add gradle.properties

            # Show the changes (for verification, optional step)
            git diff --cached

            echo "Changes staged for gradle.properties. Push to develop."
            git push origin develop
          fi
